# Generated by Django 4.0.4 on 2022-04-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userticket',
            old_name='author_id',
            new_name='author',
        ),
    ]
