# Generated by Django 4.0.4 on 2022-04-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_rename_author_id_userticket_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketstatus',
            name='url',
        ),
        migrations.RemoveField(
            model_name='userticket',
            name='name',
        ),
    ]
