# Generated by Django 4.0.4 on 2022-04-18 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_app', '0004_rename_message_data_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
