version : "3"


services:
  web:
    build:
      context: .
      dockerfile: django_docker_file
    container_name: support_app_web
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - db_keys.txt
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    container_name: postrgesql_db
    env_file:
      - db_keys.txt
    environment:
      - LANG:'ja_JP.UTF-8'
      - LANGUAGE:'ja_JP.UTF-8'
      - LC_ALL:'ja_JP.UTF-8'

  adminer:
    image: adminer:latest
    container_name: support_app_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  cache:
    image: redis:latest
    container_name: support_app_cache

  celery:
    build:
      context: .
      dockerfile: django_docker_file
    container_name: support_app_celery
    volumes:
      - ./src:/src
    env_file:
      - db_keys.txt
    depends_on:
      - db
      - cache
    command: celery -A support worker -l INFO